// pages/index.tsx
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by Next.js" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-4xl font-bold">Welcome to Next.js! 🚀</h1>
        <p className="mt-4 text-lg">This is the index page.</p>
      </main>
    </>
  );
}

["const Home: React.FC = () => {"]
const Home: React.FC = () => {
  return (
    <main className="flex flex-col h-screen justify-center items-center text-4xl font-semibold">
      <h1>Airbnb Application Clone system</h1>
    </main>
  );
};

export default Home;
