// pages/index.tsx
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by Next.js" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-4xl font-bold">Welcome to Next.js! 🚀</h1>
        <p className="mt-4 text-lg">This is the index page.</p>
      </main>
    </>
  );
}
